#!/bin/ksh

软件名称=basel
软件版本=3.11.2

typeset -A 资源链接
资源链接[basel]=https://github.com/TomWright/dasel/releases/download/v3.11.2/dasel_linux_amd64
终端命令=(basel)
typeset -A 运行路径
运行路径[basel]=软件/basel

配置部署() {

cd "$ROOT"
mkdir --parents 软件
rm --recursive --force 容器

cd "$ROOT/临时"
chmod +x basel
cp --force basel "$ROOT/软件"

}