#!/bin/ksh

软件名称=Codium
软件版本=1.135.06055

typeset -A 资源链接
资源链接[Codium.AppImage]=https://github.com/VSCodium/vscodium/releases/download/1.135.06055/VSCodium-1.135.06055-anylinux-x86_64.AppImage
终端命令=(code)
typeset -A 运行路径
运行路径[code]=临时/Codium.AppImage


配置部署() {

cd "$ROOT"
mkdir --parents 数据

cd "$ROOT/临时"
chmod +x Codium.AppImage


}