#!/bin/ksh

软件名称=FlClash
软件版本=0.8.99

终端命令=(${软件名称})
运行路径[${软件名称}]=临时/${软件名称}.AppImage
资源链接[${软件名称}.AppImage]=https://github.com/chen08209/FlClash/releases/download/v0.8.99/FlClash-0.8.99-linux-amd64.AppImage


配置部署() {

cd "$ROOT"
mkdir --parents 数据

cd "$ROOT/临时"
chmod +x ${软件名称}.AppImage

}