#!/bin/ksh

软件名称=gron
软件版本=0.7.1

typeset -A 资源链接
资源链接[gron.tgz]=https://github.com/tomnomnom/gron/releases/download/v0.7.1/gron-linux-amd64-0.7.1.tgz
终端命令=(gron)

配置部署() {

cd "$ROOT/临时"

mkdir --parents "$ROOT/容器"

mkdir --parents "$ROOT/容器/bin"
tar --extract --file gron.tgz --directory "$ROOT/容器/bin"

}