#!/bin/ksh

软件名称=Inksacpe
软件版本=1.4.4

typeset -A 资源链接
资源链接[Inkscape.AppImage]=https://www.inkscape.org/zh-hans/gallery/item/59446/Inkscape-c5dfcf2-x86_64.AppImage
终端命令=(inkscape)
typeset -A 运行路径
运行路径[inkscape]=临时/Inkscape.AppImage

配置部署() {

cd "$ROOT"
mkdir --parents 数据

cd "$ROOT/临时"
chmod +x Inkscape.AppImage

}