#!/bin/env ksh

软件名称=ksh
软件版本=5.3

终端命令=(ksh shcomp)
运行路径[ksh]=容器/bin/ksh
运行路径[shcomp]=容器/bin/shcomp
资源链接[ksh.tar.gz]=https://github.com/ksh93/ksh/archive/refs/tags/v1.0.10.tar.gz


配置部署() {

cd "$ROOT"
mkdir --parents 容器
mkdir --parents 运行

cd "$ROOT/临时"
tar --extract --file ksh.tar.gz
mv --force --no-target-directory ksh-* "$ROOT/代码"

cd "$ROOT/代码"
bin/package make
bin/package install "$ROOT/容器"

cd "$ROOT"
rm --recursive --force 代码

}