#!/bin/ksh

软件名称=Obsidian
软件版本=1.13.7

typeset -A 资源链接
资源链接[Obsidian.AppImage]=https://github.com/obsidianmd/obsidian-releases/releases/download/v1.13.7/Obsidian-1.13.7.AppImage
终端命令=(obsidian)
运行依赖=(jq)
typeset -A 运行路径
运行路径[obsidian]=临时/Obsidian.AppImage

配置部署() {

cd "$ROOT"
mkdir --parents 配置
mkdir --parents 数据

cd "$ROOT/临时"
chmod +x Obsidian.AppImage

cd "$ROOT/配置"
cat > obsidian <<'EOF'
JSON='{vaults:{"":{"path":$BASE,"open":true, "ts":""}}}'
JSON="$(jq --null-input --arg BASE "$HOME/obsidian" "$JSON")"
echo $JSON > "$HOME/.config/obsidian/obsidian.json"
EOF

cd "$ROOT/数据"
mkdir --parents .config/obsidian

}