#!/bin/ksh

软件名称=PowerShell
软件版本=7.6.6

typeset -A 资源链接
资源链接[powershell.tar.gz]=https://github.com/PowerShell/PowerShell/releases/download/v7.6.6/powershell-7.6.6-linux-x64.tar.gz
终端命令=(powershell)
typeset -A 运行路径
运行路径[powershell]=软件/pwsh

配置部署() {

cd "$ROOT"
mkdir --parents 数据
mkdir --parents 软件

cd "$ROOT/临时"
tar --extract --file powershell.tar.gz --directory "$ROOT/软件"


}