#!/bin/ksh

软件名称=Proton-tkg
软件版本=7.6.r12.g51472395

typeset -A 资源链接
资源链接[Proton.tar.gz]=https://github.com/Frogging-Family/wine-tkg-git/releases/download/7.6.r12.g51472395/proton_tkg_7.6.r12.g51472395.release.tar.gz
终端命令=(proton-tkg)
typeset -A 运行路径
运行路径[proton-tkg]=软件/proton

配置部署() {

cd "$ROOT"
mkdir --parents 数据
mkdir --parents 配置
rm --recursive --force 软件

cd "$ROOT/临时"
tar --extract --file Proton.tar.gz --directory .
mv proton_tkg_* "$ROOT/软件"

cd "$ROOT/配置"
cat > proton-ge <<'EOF'
mkdir --parents "$PREFIX"
mkdir --parents "$PREFIX/drive_c/users"
export STEAM_COMPAT_DATA_PATH="$PREFIX"
export STEAM_COMPAT_CLIENT_INSTALL_PATH=/
ln --symbolic --force --relative --no-dereference "$PREFIX" "$PREFIX/pfx"
ln --symbolic --force --relative --no-dereference "$PREFIX/drive_c/users/Public" "$PREFIX/drive_c/users/steamuser"
set -- runinprefix "$@"
EOF

}