#!/bin/ksh

软件名称=Proton
软件版本=11.0-2

typeset -A 资源链接
资源链接[proton.tar.gz]=https://github.com/ValveSoftware/Proton/archive/refs/tags/proton-11.0-2.tar.gz
终端命令=(prootn)
typeset -A 运行路径
运行路径[proton]=

配置部署() {

cd "$ROOT"
mkdir --parents 数据
mkdir --parents 代码
mkdir --parents 容器

cd "$ROOT/临时"
tar --extract --file proton.tar.gz --directory "$ROOT/代码"
cd "$ROOT/代码/Proton-proton-${软件版本}"
make --jobs=$(nproc)
make install DESTDIR="$ROOT/容器"
rm --recursive --force "$ROOT/代码"

}