#!/bin/ksh

软件名称=tcc

终端命令=(tcc)
运行路径[tcc]=容器/bin/tcc

配置部署() {

cd "$ROOT"
mkdir --parents 代码
mkdir --parents 容器
mkdir --parents 配置
rm --recursive --force 数据
rm --recursive --force 临时

cd "$ROOT/代码"
[[ -e .git ]] || git clone --single-branch --branch mob https://repo.or.cz/tinycc.git .
[[ -e .git ]] && git pull --ff-only origin mob
./configure --prefix=/
make
make install DESTDIR="$ROOT/容器"
git clean --force --directories -x

cd "$ROOT/配置"
cat > tcc << 'EOF'
set -- -L"$ROOT/容器/lib/tcc" "$@"
set -- -I"$ROOT/容器/lib/tcc/include" "$@"
EOF

}