#!/bin/ksh

软件名称=vcpkg
软件版本=2026-07-27

typeset -A 资源链接
资源链接[vcpkg]=https://github.com/microsoft/vcpkg-tool/releases/download/2026-07-27/vcpkg-glibc
终端命令=(vcpkg)
typeset -A 运行路径
运行路径[vcpkg]=临时/vcpkg

配置部署() {

cd "$ROOT"
mkdir --parents 数据
mkdir --parents 配置
git clone https://github.com/microsoft/vcpkg 代码

cd "$ROOT/临时"
chmod +x vcpkg

cd "$ROOT/配置"
cat > vcpkg << 'EOF'
export VCPKG_ROOT="$ROOT/代码"
EOF

}