#!/bin/ksh

软件名称=微信
软件版本=4.1.13

typeset -A 资源链接
资源链接[${软件名称}.AppImage]=https://dldir1v6.qq.com/weixin/Universal/Linux/WeChatLinux_x86_64.AppImage
终端命令=(${软件名称})
typeset -A 运行路径
运行路径[${软件名称}]=临时/${软件名称}.AppImage

配置部署() {

cd "$ROOT"
mkdir --parents 数据

cd "$ROOT/临时"
chmod +x ${软件名称}.AppImage
./${软件名称}.AppImage --appimage-extract
cp --force --dereference squashfs-root/.DirIcon "$ROOT/图标/${软件名称}.$(file --extension --brief squashfs-root/.DirIcon)"
rm --recursive --force squashfs-root

cd "$ROOT/打开"
cat > ${软件名称}.desktop << EOF
[Desktop Entry]
Type=Application
Terminal=false
Name=${软件名称}
Exec=${软件名称}
Icon=${软件名称}
EOF

}