#!/bin/ksh

软件名称=火狐浏览器

终端命令=(firefox)
运行路径[firefox]=软件/firefox
资源链接[firefox.tar.xz]=https://download-installer.cdn.mozilla.net/pub/firefox/nightly/latest-mozilla-central-l10n/firefox-158.0a1.zh-CN.linux-x86_64.tar.xz

配置部署() {

cd "$ROOT"
mkdir --parents 配置
mkdir --parents 数据
rm --recursive --force 容器

cd "$ROOT/临时"
tar --extract --file firefox.tar.xz --directory .
[[ -d "$ROOT/软件" ]] || cp --recursive --force --no-target-directory firefox "$ROOT/软件"
cp --force "$ROOT/软件/browser/chrome/icons/default/default128.png" "$ROOT/系统/icons/${软件名称}.png"
rm --recursive --force firefox

cd "$ROOT/配置"
cat > firefox <<'EOF'
Home=$(eval echo ~$USER)
export XDG_CACHE_HOME="$Home/.cache"
export XDG_CONFIG_HOME="$Home/.config"
export XDG_DATA_HOME="$Home/.local/share"
export XDG_STATE_HOME="$Home/.local/state"
set -- "$@" -P Profile
EOF

cd "$ROOT/系统"
cat > autostart/${软件名称}.desktop << TEXT
[Desktop Entry]
Type=Application
Exec=firefox
Name=${软件名称}
Icon=${软件名称}
TEXT
cat > applications/${软件名称}.desktop << TEXT
[Desktop Entry]
Type=Application
Exec=firefox
Name=${软件名称}
Icon=${软件名称}
TEXT



}