#!/bin/ksh

软件名称=金山文档
软件版本=12.1.2.28080

typeset -A 资源链接
资源链接[wps-office.deb]=https://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/linux/11723/wps-office_11.1.0.11723.XA_amd64.deb
终端命令=(et wps wpp)
typeset -A 运行路径
运行路径[et]=容器/opt/kingsoft/wps-office/office6/et
运行路径[wps]=容器/opt/kingsoft/wps-office/office6/wps
运行路径[wpp]=容器/opt/kingsoft/wps-office/office6/wpp

配置部署() {

cd "$ROOT"
mkdir --parents 容器
mkdir --parents 数据

cd "$ROOT/临时"
ar x wps-office.deb
tar --extract --file data.tar.* --directory "$ROOT/容器"
rm --force data.tar.*
rm --force control.tar.*
rm --force debian-binary


}