#!/bin/ksh

运行命令="$1"

脚本路径="$(realpath "$0")"
起始路径="$(dirname "${脚本路径}")"

方式列表="${起始路径}/运行方式"
数据仓库="${起始路径}/数据仓库"
共享文件="${起始路径}/共享文件"
软件列表="${起始路径}/软件列表"
软件依赖="${起始路径}/软件依赖"
软件仓库="${起始路径}/软件仓库"

export PATH="$HOME/软件/软件运行:$PATH"


# cd "${起始路径}"
# git fetch --all

if [[ "${运行命令}" == "运行" ]];then
    
    软件目录="$ROOT"
    软件运行="${软件目录}/运行"
    软件配置="${软件目录}/配置"
    临时目录="${软件目录}/临时"
    容器目录="${软件目录}/容器"
    
    [[ -f "${软件运行}" ]] || { echo "缺少运行文件:${软件运行}";exit; }
    [[ -f "${软件配置}" ]] || { echo "缺少配置文件:${软件配置}";exit; }
    
    [[ -f "${软件配置}" ]] && source "${软件配置}"
    软件路径="${软件列表}/${软件名称}"
    [[ -d "${软件路径}" ]] && cp --recursive --force "${软件路径}/." "${软件目录}"
    cp --recursive --force "${共享文件}/." "${软件目录}"

    [[ -f "${软件配置}" ]] && source "${软件配置}"
    运行参数=("${@:2}")
    ( 更新检查 ) &
    配置部署
    运行环境

    if [[ -n "${运行依赖}" ]];then
        for 依赖名称  in "${运行依赖[@]}"; do
            软件管理 依赖 "${依赖名称}"
        done
    fi
    运行路径="$ROOT/${运行路径}"
    if [[ "${图标路径}" != https://* ]];then
        ln --symbolic --force "${图标路径}" "$ROOT/图标"
    fi
    chmod +x "${方式列表}/${运行方式}"
    exec "${方式列表}/${运行方式}" "${运行路径}" "${运行参数[@]}"

fi

if [[ "${运行命令}" == "部署" ]];then

    软件名称="$2"
    软件目录="$PWD/${软件名称}"
    软件运行="${软件目录}/运行"
    软件路径="${软件列表}/${软件名称}"
    
    [[ -z "${软件名称}" ]] && { echo "缺少参数软件名称: 软件管理 部署 软件名称";exit; }
    [[ -d "${软件目录}" ]] && { echo "软件已经存在请勿重复部署软件:${软件名称}";exit; }
    [[ -d "${软件路径}" ]] || { echo "软件列表里面没有找到这个软件:${软件名称}";exit; }

    mkdir --parents "${软件目录}"
    cp --recursive --force "${软件路径}"/* "${软件目录}"
    cp --recursive --force "${共享文件}"/* "${软件目录}"
    chmod +x "${软件运行}"

fi


if [[ "${运行命令}" == "依赖" ]];then

    软件名称="$2"
    依赖路径="${软件依赖}/${软件名称}"

    source "${依赖路径}"
    export ROOT="$HOME/软件/软件仓库/${软件名称}"


    临时目录="$ROOT/临时"
    容器目录="$ROOT/容器"
    软件目录="$ROOT/软件"
    运行目录="$ROOT/运行"

    mkdir --parents "$ROOT"
    mkdir --parents "${临时目录}"
    

    cd "${临时目录}"

    if [[ "${软件版本}" != "$(cat "$ROOT/版本")" ]];then
        ;
    fi

    for 文件名称 in "${!资源链接[@]}"; do
        [[ -z "${文件名称}" ]] && continue
        文件链接="${资源链接[${文件名称}]}"
        [[ -z "${文件链接}" ]] && continue
        [[ -f "${文件名称}" ]] || wget --output-document="${文件名称}" "${文件链接}"
    done

    配置部署
    for 运行命令 in "${终端命令[@]}"; do
        ln --symbolic --force --relative "${运行目录}/${运行命令}" "$HOME/软件/软件运行/${运行命令}"
    done

    mkdir --parents "$ROOT/运行"
    for 文件名称 in "${!运行路径[@]}"; do
        相对路径="${运行路径[${文件名称}]}"
        echo '#!/bin/env dash' > "$ROOT/运行/${文件名称}"
        echo 'FILE="$(realpath "$0")"' >> "$ROOT/运行/${文件名称}"
        echo 'ROOT="$(dirname "$FILE")"' >> "$ROOT/运行/${文件名称}"
        echo 'ROOT="$(dirname "$ROOT")"' >> "$ROOT/运行/${文件名称}"
        echo 'LIST="$(dirname "$ROOT")"' >> "$ROOT/运行/${文件名称}"
        echo 'NAME="$(basename "$FILE")"' >> "$ROOT/运行/${文件名称}"
        for 软件名称 in "${运行依赖[@]}"; do
            [[ -z "${软件名称}" ]] && continue
            echo 'export PATH="$LIST/'${软件名称}'/运行:$PATH"' >> "$ROOT/运行/${文件名称}"
        done
        for 软件名称 in "${动态链接[@]}"; do
        [[ -z "${软件名称}" ]] && continue
            echo 'export LD_LIBRARY_PATH="$LIST/'${软件名称}'/共享:$LD_LIBRARY_PATH"' >> "$ROOT/运行/${文件名称}"
        done
        [[ -d "$ROOT/容器/lib" ]] && echo 'export LD_LIBRARY_PATH="$ROOT/容器/lib:$LD_LIBRARY_PATH"' >> "$ROOT/运行/${文件名称}"
        [[ -e "$ROOT/数据" ]] && echo 'export HOME="$ROOT/数据"' >> "$ROOT/运行/${文件名称}"
        [[ -f "$ROOT/配置/${文件名称}" ]] && echo '. "$ROOT/配置/$NAME"' >> "$ROOT/运行/${文件名称}"
        echo 'exec "$ROOT/'${相对路径}'" "$@"' >> "$ROOT/运行/${文件名称}"
        chmod +x "$ROOT/运行/${文件名称}"
    done



    echo "${软件版本}" > "$ROOT/版本"

fi


# if [[ "${运行命令}" == "软件" ]];then

#     软件名称="$2"
#     依赖路径="${软件仓库}/${软件名称}"

#     source "${依赖路径}"
#     export ROOT="$HOME/软件/软件仓库/${软件名称}"

#     [[ "${软件版本}" == "$(cat "$ROOT/版本")" ]]  && exit

#     mkdir --parents "$ROOT"
#     mkdir --parents "${临时目录}"
    
#     cd "${临时目录}"
#     for 文件名称 in "${!资源链接[@]}"; do
#         [[ -z "${文件名称}" ]] && continue
#         文件链接="${资源链接[${文件名称}]}"
#         [[ -z "${文件链接}" ]] && continue
#         [[ -f "${文件名称}" ]] || wget --output-document="${文件名称}" "${文件链接}"
#     done
#     配置部署
#     for 运行命令  in "${终端命令[@]}"; do
#         ln --symbolic --force --relative "${运行目录}/${运行命令}" "$HOME/软件/软件运行/${运行命令}"
#     done
#     echo "${软件版本}" > "$ROOT/版本"

# fi



if [[ "${运行命令}" == "全部更新" ]];then
    软件列表="$HOME/软件/软件仓库"
    cd "${软件列表}"
    for 软件名称 in *; do
        软件管理 依赖 "${软件名称}"
    done
fi  